Add additional configuration options
intelsdi-x/swan pull request #588
Opened 2017-04-07 10:23 UTC by squall0gd

Fixes issue ...

Summary of changes:
- Add additional configuration flags for cassandra

Help needed:
- Test this code with updated cassandra publisher

TBD:
- [x] Commentaries
- [x] Unit tests
- [ ] Ensure schema consistency

Testing done:
-

2017-04-07 11:22 UTC, ppalucki requested changes
you need to update the cassandra-plugin version in provision.sh as well

2017-05-08 12:09 UTC, squall0gd commented
run integration tests

2017-05-08 12:23 UTC, squall0gd commented
Blocked by https://github.com/intelsdi-x/snap-plugin-publisher-cassandra/pull/31

2017-05-10 14:29 UTC, squall0gd commented
Working integration tests: ![screenshot from 2017-05-10 16-24-19](https://cloud.githubusercontent.com/assets/9694425/25903846/dde2c946-359d-11e7-90e4-84ac09935638.png)

2017-05-18 07:38 UTC, skonefal commented on NOTICE
> +This software contains portions of kubernetes/kubernetes from https://github.com/kubernetes/kubernetes,
We can drop it now :)

2017-05-18 11:39 UTC, iwankgb commented on NOTICE
> +This software contains portions of kubernetes/kubernetes from https://github.com/kubernetes/kubernetes,
@squall0gd - rebase against `master`, please.

2017-05-18 11:50 UTC, iwankgb requested changes

2017-05-18 11:50 UTC, iwankgb commented on pkg/conf/flags.go
> +var CassandraTimeout = NewIntFlag("cassandra_timeout", "Query timeout for the publisher in seconds.", 0)
@squall0gd - use [`DurationFlag`](https://github.com/intelsdi-x/swan/blob/master/pkg/conf/flag.go#L145) instead.

2017-05-18 11:50 UTC, iwankgb commented on pkg/experiment/metadata.go
> +	config := m.connect()
@squall0gd - why variable that represents datatabase connection is called `config`?

2017-05-18 11:50 UTC, iwankgb commented on pkg/experiment/metadata.go
> +	// // NOTE: Schema consistency check is ignored by CREATE query. (https://git-wip-us.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=doc/native_protocol_v4.spec)
@squall0gd - removed some of the slashes, please.

2017-05-18 11:50 UTC, iwankgb commented on pkg/experiment/metadata.go
> +	// // NOTE: Same issue as above.
@squall0gd - remove extra slashes, please.

2017-05-19 07:52 UTC, skonefal commented on pkg/conf/flags.go
> +var CassandraInitialHostLookup = NewBoolFlag("cassandra_initial_host_loopup", "If false, driver won't attempt to get host info from Cassandra.", true)
Could you elaborate, in what situation, getting host info from Cassandra is necessary?

2017-05-19 07:53 UTC, skonefal commented on pkg/conf/flags.go
> +var CassandraKeyspaceName = NewStringFlag("cassandra_keyspace_name", "Keyspace name used by driver.", "swan")
Instead of 'driver' notion, we should rather say that this is keyspace used to store metadata.

2017-05-19 07:58 UTC, skonefal commented on pkg/experiment/metadata.go
>  func DefaultMetadataConfig() MetadataConfig {
Are those defaults differs from `MetadataConfigFromFlags`? If not, maybe we could drop one of them?

2017-05-19 08:00 UTC, skonefal commented on pkg/experiment/metadata.go
> +	defer session.Close()
You should't defer this before checking error.

2017-05-19 08:01 UTC, skonefal commented on pkg/experiment/metadata.go
> +		return fmt.Errorf("cannot achieve session for creating keyspace: %q", err.Error())
Please use `github.com/pkg/errors`.
/s/achieve/create

2017-05-19 08:01 UTC, skonefal commented on pkg/experiment/metadata.go
> +	return session.Query(query).Exec()
You should wrap the received error in `github.com/pkg/errors` so that we could see stack trace if something goes wrong.

2017-05-19 08:03 UTC, skonefal commented on pkg/experiment/metadata.go
> +func (m *Metadata) Connect() error {
Do you think it would be wise to `connect` during Metadata object creation? So that initialized object would be ready to use.

2017-05-24 10:48 UTC, squall0gd commented on pkg/conf/flags.go
> +var CassandraInitialHostLookup = NewBoolFlag("cassandra_initial_host_loopup", "If false, driver won't attempt to get host info from Cassandra.", true)
- Could bring some internal cluster information like: more information [here](https://github.com/gocql/gocql/blob/master/cluster.go#L93)
- It was used before, so we don't break any backward compatibility

2017-05-24 10:48 UTC, squall0gd commented on pkg/experiment/metadata.go
>  func DefaultMetadataConfig() MetadataConfig {
can we do this in following PR? IMO it's expending scope of this never_ending_story task

2017-05-24 10:48 UTC, squall0gd commented on pkg/experiment/metadata.go
> +	defer session.Close()
But I'm defering this before checking error oO

2017-05-24 10:48 UTC, squall0gd commented on pkg/experiment/metadata.go
> +	// // NOTE: Schema consistency check is ignored by CREATE query. (https://git-wip-us.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=doc/native_protocol_v4.spec)
this comments could be dropped b/c I don't see any reason to check that keyspace is created

2017-05-24 10:48 UTC, squall0gd commented on pkg/experiment/metadata.go
> +	// // NOTE: Same issue as above.
same here

2017-05-24 11:32 UTC, squall0gd commented on pkg/experiment/metadata.go
> +	config := m.connect()
b/c `m.connect()` returns `ClusterConfig` ;)

2017-05-24 11:39 UTC, squall0gd commented on pkg/experiment/metadata.go
> +	config := m.connect()
I've renamed it to `connectionConfiguration`

2017-05-24 11:47 UTC, squall0gd commented on pkg/experiment/metadata.go
> +func (m *Metadata) Connect() error {
this also is a expending this PR imho. But, in the future, We can make `session` object once and then reuse it, so we don't lose cycles on creating connection to cluster

2017-05-24 19:20 UTC, iwankgb requested changes

2017-05-24 19:20 UTC, iwankgb commented on NOTICE
> +This software contains portions of kubernetes/kubernetes from https://github.com/kubernetes/kubernetes,
@squall0gd - for some reason you want to replace `NOTICE` with outdated version. Fix it, please.

2017-05-25 08:06 UTC, skonefal commented on pkg/experiment/metadata.go
> +func (m *Metadata) Connect() error {
Sure, good idea.

2017-05-25 08:07 UTC, skonefal commented on pkg/experiment/metadata.go
>  func DefaultMetadataConfig() MetadataConfig {
Sure, of course.

2017-05-25 11:36 UTC, squall0gd commented
run integration tests

2017-05-25 12:22 UTC, squall0gd commented
run integration tests

2017-05-25 14:11 UTC, squall0gd commented
run integration tests

2017-05-25 14:22 UTC, squall0gd commented
run integration tests

2017-05-25 14:39 UTC, squall0gd commented
run integration tests

2017-05-25 15:26 UTC, squall0gd commented
run integration tests

2017-05-25 15:51 UTC, iwankgb approved these changes

2017-05-25 15:56 UTC, ppalucki approved these changes

2017-05-25 15:58 UTC, merged